FROM alpine:3.12

RUN apk add ansible py-pip

RUN apk add bash git openssh-client

RUN adduser -h /home/ansible -s /bin/bash ansible -D

RUN mkdir /home/ansible/.ssh /opt/config

COPY ssh_config.sh /home/ansible 

RUN chown -R ansible:ansible /home/ansible

RUN chown -R ansible:ansible /opt/config

USER ansible

WORKDIR /home/ansible

CMD ["/bin/bash"]

