# Sample manifest for AnsibleJob with playbook in Kubernetes secret
---
apiVersion: ansible.casa-delle-coccinelle.link/v1alpha1
kind: AnsibleJob
metadata:
  name: ansiblejob-example
  namespace: operator-example
spec:
  playbook:
    # Secret "playbook-secret" will mounted onto executor's pod and defined playbook will be executed
    secretRef:
      name: playbook-secret
  # These roles and collection will be installed, too
  roles:
  - name: example.role
    src: example.role.source
  - name: another.role
    src: git+ssh://git@github.com/example/another-role.git
    version: master
  collections:
  - name: ansible.posix
    version: 1.2.0
  # Ansible vault password can be defined directly in CRD. In this case operator will create secret with the password with name ansiblejob-example-vault
  vault_password: "a-vault-password"
  # Secret with ansible inventory
  inventory:
    - secretRef:
        name: inventory
  # Ansible playbook variables can be defined as name/value pairs, in secret and in configmap. All variables will be supplied to the playbook. Operator will mount configmap and secret onto executor's pod and create a configmap with name/value definitions.
  additional_vars:
    - name: var1
      value: value1
    - name: var2
      value: 1
    - name: var3
      value: "true"
    - name: var4
      value: "3.51"
    - secretRef:
        name: vars-secret
    - configMapRef:
        name: vars-configmap
  additional_ansible_options:
    - --start-at-task "Some task"
    - --force-handlers

# Secret with ansible playbook. If more than one data is provided, the executor will exit with an error.
---
apiVersion: v1
kind: Secret
metadata:
  name: playbook-secret
  namespace: operator-example
stringData:
  playbook.yaml: |
    ---
    - hosts: localhost
      vars:
        secret: "confidential"
      roles:
        - example.role
        - another.role

# Ansible inventory with credentials should be defined as Kubernetes secrets. More than one inventory file can be added to the secret.
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory
  namespace: operator-example
stringData:
  inventory: |
    [server]
    172.16.1.3 ansible_user=user ansible_password=password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-configmap
  namespace: operator-example
data:
  vars.yaml: |
    var: "value"
    another_var: "another_value"

---
apiVersion: v1
kind: Secret
metadata:
  name: vars-secret
  namespace: operator-example
stringData:
  vars.yaml: |
    secret_var: "secret-value"
    another_secret_var: "another-secret-value"


# With this configuration the playbook command will be:
# ansible-playbook playbook.yaml --vault-password-file ansiblejob-example-vault -i inventory -e @vars-configmap/vars.yaml -e @vars-secret/vars.yaml -e @path/to/created/additonal_vars_configmap.yaml --start-at-task "Some task" --force-handlers
