---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "ansible-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: kube-rbac-proxy
        image: {{ .Values.proxyImage.repository }}:{{ .Values.managerImage.tag }}
        imagePullPolicy: {{ .Values.proxyImage.pullPolicy }}
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      - name: manager
        image: {{ .Values.managerImage.repository }}:{{ .Values.managerImage.tag }}
        imagePullPolicy: {{ .Values.managerImage.pullPolicy }}
        args:
        {{- include "ansible-operator.manager-args" . | nindent 8 -}}
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        {{- if .Values.probes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthProbeBindAddress }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        {{- end -}}
        {{ if .Values.probes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthProbeBindAddress }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
        {{- end }}
        {{- if .Values.resources.manager }}
        resources:
          {{- .Values.resources.manager | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.securityContext.manager }}
        securityContext:
          {{- .Values.securityContext.manager | toYaml | nindent 10 }}
        {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: 
        {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ansible-operator.serviceAccountName" . }} 
      terminationGracePeriodSeconds: 10
