---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ansible-operator.fullname" . | trunc 47 }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ansible-operator.fullname" . | trunc 55 }}-manager
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible.casa-delle-coccinelle.link
  resources:
  - ansiblejobs
  - ansiblejobs/status
  - ansiblejobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible.casa-delle-coccinelle.link
  resources:
  - ansiblecrons
  - ansiblecrons/status
  - ansiblecrons/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ansible-operator.fullname" . | trunc 48 }}-metrics-reader
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ansible-operator.fullname" . | trunc 47 }}-leader-election
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ansible-operator.fullname" . | trunc 47 }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "ansible-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ansible-operator.fullname" . | trunc 55 }}-manager
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ansible-operator.fullname" . | trunc 55 }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "ansible-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

