---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ansible-operator.serviceAccountName" . }}
  labels:
    {{- include "ansible-operator.labels" . | nindent 4 }}
  {{- include "ansible-operator.serviceAccountAnnotations" . | nindent 2 }}
