replicaCount: 1

image:
  # TODO Switch to github 
  repository: c-harbor.casa-delle-coccinelle.link/operator/ansible-operator 
  pullPolicy: IfNotPresent
  tag: v0.1.0

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: ""

podAnnotations: {}

chartWideAnnotations: {}

managerArgs: []

managerEnv:
  - name: ANSIBLE_GATHERING
    value: explicit

healthProbeBindAddress: 6789

metrics:
  enabled: true
  port: 8080

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 10m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
