# permissions for end users to view ansiblejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansiblejob-viewer-role
rules:
- apiGroups:
  - ansible.casa-delle-coccinelle.link
  resources:
  - ansiblejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ansible.casa-delle-coccinelle.link
  resources:
  - ansiblejobs/status
  verbs:
  - get
