---
- name: Include secrets tasks
  include_tasks: secrets.yaml

- name: Include configmaps tasks
  include_tasks: configmaps.yml

- name: Deploy cronjob
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', './ansible_cronjob.j2') }}"
