---
- name: Create vault password secret if defined
  kubernetes.core.k8s:
    template: vault_secret.j2
  when: vault_password is defined

- name: Create ssh secret if defined
  kubernetes.core.k8s:
    template: ssh_secret.j2
  loop: "{{ ssh_keys }}"
  loop_control:
    index_var: index
    loop_var: key
  when: ssh_keys is defined
  no_log: yes
  register: keys

- name: set secrets fact
  ansible.builtin.set_fact:
    keys_list: "{{ keys_list }} + [ '{{ item.result.metadata.name }}' ]"
  with_items: "{{ keys.results }}"
  no_log: yes
  vars:
    keys_list: []
  when: ssh_keys is defined

- name: debug
  debug:
    var: ssh_keys_secrets
